stages:
  - test
  - build
  - deploy
  - performance

variables:
  CONTAINER_DEV_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  CONTAINER_PROD_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  CI_DEVELOPMENT_BRANCH: dev
  CI_PROD: production
  CI_DEV: development
  CI_PROD_URL: http://192.168.200.100
  CI_DEV_URL: http://192.168.200.100
  CI_PROD_PORT: 7080
  CI_DEV_PORT: 6080

build_dev:
  stage: build
  tags:
    - docker
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^dev.*/
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
  script:
    - echo "--- build_dev ---"
    - docker build -t $CONTAINER_DEV_IMAGE -f Dockerfile.prod .
    - docker push $CONTAINER_DEV_IMAGE

build_prod:
  stage: build
  tags:
    - docker
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^release.*/
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
  script:
    - echo "--- build_prod ---"
    - docker build -t $CONTAINER_PROD_IMAGE -f Dockerfile.dev .
    - docker push $CONTAINER_PROD_IMAGE

deploy_dev:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  tags:
    - docker
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^dev.*/
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
  script:
    - echo "--- deploy_dev ---"
    - docker run -d -p $CI_DEV_PORT:80 --restart always --name $CI_COMMIT_TAG $CONTAINER_DEV_IMAGE

deploy_prod:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  tags:
    - docker
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^release.*/
  environment:
    name: $CI_PROD
    url: $CI_PROD_URL:$CI_PROD_PORT
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
  script:
    - echo "--- deploy_prod ---"
    - docker run -d -p $CI_PROD_PORT:80 --restart=always --name $CI_COMMIT_TAG $CONTAINER_TEST_IMAGE
performance_dev:
  stage: performance
